name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          build: npm run build
          start: npm start
